# Generated by Django 5.1.4 on 2024-12-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portman', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
