# Generated by Django 5.1.4 on 2025-01-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portman', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com', null=True),
        ),
    ]
