# Generated by Django 5.1.4 on 2025-01-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portman', '0013_alter_profile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Link to the live version of the project', null=True),
        ),
    ]
