# Generated by Django 5.1.4 on 2025-01-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portman', '0010_alter_profile_user_alter_publication_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the publication'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
