# Generated by Django 5.1.4 on 2025-03-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portman', '0015_profile_location_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_year',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_year',
            new_name='start_date',
        ),
    ]
