# Generated by Django 5.1.4 on 2025-03-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portman', '0016_rename_end_year_education_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='appwrite_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
